---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tenants
  namespace: flux-system
spec:
  interval: 5s
  serviceAccountName: kustomize-controller
  path: ./tenants/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
