apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base/team1
- ../base/team2
- team1-quota.yaml
- team2-quota.yaml
patches:
- path: team1-patch.yaml
- path: team2-patch.yaml
