---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: team2
  namespace: apps2
spec:
  interval: 5s
  ref:
    branch: main
  url: https://github.com/allymparker/was_team2

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: team2
  namespace: apps2
spec:
  interval: 5s
  path: ./
  prune: true
  serviceAccountName: team2
  sourceRef:
    kind: GitRepository
    name: team2

