---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: team1
  namespace: team1
spec:
  interval: 5s
  ref:
    branch: main
  url: https://github.com/allymparker/was_team1

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: team1
  namespace: team1
spec:
  interval: 5s
  path: ./
  prune: false
  serviceAccountName: team1
  sourceRef:
    kind: GitRepository
    name: team1
