apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 720m0s
  sourceRef:
    kind: GitRepository
    name: ingress-nginx
  serviceAccountName: kustomize-controller
  path: ./deploy/static/provider/cloud/deploy.yaml
  prune: true
  wait: true
  timeout: 5m
